apiVersion: apps/v1
kind: Deployment
metadata:
  name: swampup23-backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    spec:
      containers:
        - name: backend
          replicas: 1