apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: swampup-backend
    newName: nvsswampup.jfrog.io/swamp-up-24-docker/jfrog-demo
    newTag: 0.0.1-SNAPSHOT-20240904-201445
patchesStrategicMerge:
  - deployment-replicas.yaml
