apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: swampup-backend
    newName: nvsconsulting.jfrog.io/cicd-demo-container-images/swampup23/jfrog-demo
    newTag: nvsconsulting.jfrog.io/cicd-demo-container-images/swampup23/jfrog-demo:0.0.1-SNAPSHOT-20230911-012451
