apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: swampup-backend
    newName: nvsconsulting.jfrog.io/cicd-demo-container-images/swampup23/jfrog-demo
    newTag: 1.0.0-SNAPSHOT-20230913-214839
patchesStrategicMerge:
  - deployment-replicas.yaml
